---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "server.fullname" . }}-ingress
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "server.selectorLabels" . | nindent 6 }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.ingress.namespaceSelector | nindent 14 }}
        - podSelector:
            matchLabels:
              {{- toYaml .Values.server.networkPolicy.ingress.podSelector | nindent 14 }}
  policyTypes:
    - Ingress