---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "global.postgresql.fullname" . }}-ingress
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "postgresql.selectorLabels" . | nindent 6 }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.ingress.namespaceSelector | nindent 14 }}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "global.postgresql.fullname" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "postgresql.selectorLabels" . | nindent 6 }}
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.postgresql.primary.service.ports.postgresql }}
      from:
        - podSelector:
            matchLabels:
              {{- include "server.selectorLabels" . | nindent 14 }}
  policyTypes:
    - Ingress